version: '3.8'

services:
  app:
    build: .
    ports:
      - 9090:9090
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=qwerty
      - DB_NAME=postgres
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
